In [1]:
import pandas as pd
import datetime as dt
from datetime import datetime

In [2]:
data = pd.read_csv("/home/xena/Desktop/prateek/oneGo/onego_poc1/files/scraped_data/paytm_flights_50_schedule.csv", sep =",")

/home/xena/miniconda3/envs/onego/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.loc[data.Dept_Date == '2019-11-15']

,RecordDate,Airline,Flight,Dept_Date,Dept_Time,Origin,Duration,Stops,Arr_Date,Arr_Time,Destination,Total_Fare,dummy_comma1,dummy_comma2
236761,2019-09-01 23:47:19,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,AMD-Ahmedabad,NaN,NaN,NaN
236762,2019-09-01 23:47:31,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,ATQ-Amritsar,NaN,NaN,NaN
236763,2019-09-01 23:47:44,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BBI-Bhubaneswar,NaN,NaN,NaN
236764,2019-09-01 23:47:56,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BDQ-Vadodara,NaN,NaN,NaN
236765,2019-09-01 23:48:09,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BHJ-Bhuj,NaN,NaN,NaN
236766,2019-09-01 23:48:21,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BHU-Bhavnagar,NaN,NaN,NaN
236767,2019-09-01 23:48:34,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BLR-Bangalore,NaN,NaN,NaN
236768,2019-09-01 23:48:46,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,BOM-Mumbai,NaN,NaN,NaN
236769,2019-09-01 23:48:59,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,CCJ-Calicut,NaN,NaN,NaN
236770,2019-09-01 23:49:12,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,CCU-Kolkata,NaN,NaN,NaN
236771,2019-09-01 23:49:25,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,CJB-Coimbatore,NaN,NaN,NaN
236772,2019-09-01 23:49:37,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,COK-Kochi,NaN,NaN,NaN
236773,2019-09-01 23:49:50,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,DED-Dehra Dun,NaN,NaN,NaN
236774,2019-09-01 23:50:02,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,DEL-New Delhi,NaN,NaN,NaN
236775,2019-09-01 23:50:14,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,DIU-Diu,NaN,NaN,NaN
236776,2019-09-01 23:50:27,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,GAU-Guwahati,NaN,NaN,NaN
236777,2019-09-01 23:50:39,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,GOI-Goa,NaN,NaN,NaN
236778,2019-09-01 23:50:52,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,HYD-Hyderabad,NaN,NaN,NaN
236779,2019-09-01 23:51:05,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IDR-Indore,NaN,NaN,NaN
236780,2019-09-01 23:51:17,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IMF-Imphal,NaN,NaN,NaN
236781,2019-09-01 23:51:31,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXA-Agartala,NaN,NaN,NaN
236782,2019-09-01 23:51:44,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXB-Siliguri,NaN,NaN,NaN
236783,2019-09-01 23:51:57,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXC-Chandigarh,NaN,NaN,NaN
236784,2019-09-01 23:52:09,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXE-Mangalore,NaN,NaN,NaN
236785,2019-09-01 23:52:24,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXJ-Jammu,NaN,NaN,NaN
236786,2019-09-01 23:52:37,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXL-Leh,NaN,NaN,NaN
236787,2019-09-01 23:52:49,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXM-Madurai,NaN,NaN,NaN
236788,2019-09-01 23:53:02,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXR-Ranchi,NaN,NaN,NaN
236789,2019-09-01 23:53:14,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,IXZ-Port Blair,NaN,NaN,NaN
236790,2019-09-01 23:53:27,NaN,NaN,2019-11-15,NaN,AGR-Agra,NaN,NaN,NaN,NaN,JAI-Jaipur,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402574,2019-09-09 23:50:45,Air India,AI - 452,2019-11-15,08:40,VTZ,23h 35m,1 Stop,NaN,08:15,VGA,"10,325",NaN,NaN
402575,2019-09-09 23:50:45,Air India,AI - 488,2019-11-15,15:15,VTZ,17h 0m,1 Stop,NaN,08:15,VGA,"10,325",NaN,NaN
402576,2019-09-09 23:50:45,Air India,AI - 452,2019-11-15,08:40,VTZ,8h 15m,2 Stops,NaN,16:55,VGA,"10,325",NaN,NaN
402577,2019-09-09 23:50:45,Air India,AI - 452,2019-11-15,08:40,VTZ,11h 20m,1 Stop,NaN,20:00,VGA,"10,535",NaN,NaN
402578,2019-09-09 23:50:45,Air India,AI - 488,2019-11-15,15:15,VTZ,28h 45m,1 Stop,NaN,20:00,VGA,"10,535",NaN,NaN
402579,2019-09-09 23:50:45,Air India,AI - 486,2019-11-15,12:30,VTZ,7h 30m,1 Stop,NaN,20:00,VGA,"10,535",NaN,NaN
402580,2019-09-09 23:50:45,Air India,AI - 651,2019-11-15,14:15,VTZ,26h 40m,2 Stops,NaN,16:55,VGA,"10,695",NaN,NaN
402581,2019-09-09 23:50:45,Air India,AI - 651,2019-11-15,14:15,VTZ,26h 40m,2 Stops,NaN,16:55,VGA,"10,695",NaN,NaN
402582,2019-09-09 23:50:45,Air India,AI - 651,2019-11-15,14:15,VTZ,26h 40m,2 Stops,NaN,16:55,VGA,"11,220",NaN,NaN
402583,2019-09-09 23:50:58,SpiceJet,SG - 422,2019-11-15,09:20,VTZ,9h 55m,1 Stop,NaN,19:15,VNS,"6,643",NaN,NaN
402584,2019-09-09 23:50:58,IndiGo,6E - 2726,2019-11-15,08:55,VTZ,9h 0m,1 Stop,NaN,17:55,VNS,"6,647",NaN,NaN
402585,2019-09-09 23:50:58,IndiGo,6E - 287,2019-11-15,07:45,VTZ,10h 5m,1 Stop,NaN,17:50,VNS,"7,040",NaN,NaN
402586,2019-09-09 23:50:58,IndiGo,6E - 809,2019-11-15,12:55,VTZ,4h 45m,1 Stop,NaN,17:40,VNS,"8,865",NaN,NaN
402587,2019-09-09 23:50:58,Air India,AI - 486,2019-11-15,12:30,VTZ,26h 20m,2 Stops,NaN,14:50,VNS,"9,590",NaN,NaN
402588,2019-09-09 23:50:58,Air India,AI - 488,2019-11-15,15:15,VTZ,23h 35m,2 Stops,NaN,14:50,VNS,"9,590",NaN,NaN
402589,2019-09-09 23:50:58,Air India,AI - 488,2019-11-15,15:15,VTZ,27h 25m,1 Stop,NaN,18:40,VNS,"9,800",NaN,NaN
402590,2019-09-09 23:50:58,IndiGo,6E - 809,2019-11-15,12:55,VTZ,7h 15m,2 Stops,NaN,20:10,VNS,"10,933",NaN,NaN
402591,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,20h 50m,3 Stops,NaN,14:50,VNS,"11,342",NaN,NaN
402592,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,24h 40m,2 Stops,NaN,18:40,VNS,"11,552",NaN,NaN
402593,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,20h 50m,3 Stops,NaN,14:50,VNS,"12,427",NaN,NaN
402594,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,24h 40m,2 Stops,NaN,18:40,VNS,"12,637",NaN,NaN
402595,2019-09-09 23:50:58,Air India,AI - 452,2019-11-15,08:40,VTZ,26h 55m,1 Stop,NaN,11:35,VNS,"13,265",NaN,NaN
402596,2019-09-09 23:50:58,Air India,AI - 488,2019-11-15,15:15,VTZ,20h 20m,1 Stop,NaN,11:35,VNS,"13,265",NaN,NaN
402597,2019-09-09 23:50:58,Air India,AI - 486,2019-11-15,12:30,VTZ,23h 5m,1 Stop,NaN,11:35,VNS,"13,265",NaN,NaN
402598,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,18h 40m,2 Stops,NaN,12:40,VNS,"13,477",NaN,NaN
402599,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,18h 40m,2 Stops,NaN,12:40,VNS,"13,494",NaN,NaN
402600,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,24h 40m,2 Stops,NaN,18:40,VNS,"13,687",NaN,NaN
402601,2019-09-09 23:50:58,Air India,AI - 651,2019-11-15,14:15,VTZ,22h 25m,1 Stop,NaN,12:40,VNS,"14,053",NaN,NaN
402602,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,17h 35m,2 Stops,NaN,11:35,VNS,"15,017",NaN,NaN
402603,2019-09-09 23:50:58,Air India,AI - 951,2019-11-15,18:00,VTZ,17h 35m,2 Stops,NaN,11:35,VNS,"16,102",NaN,NaN

In [4]:
data.columns

Index(['RecordDate', 'Airline', 'Flight', 'Dept_Date', 'Dept_Time', 'Origin',
       'Duration', 'Stops', 'Arr_Date', 'Arr_Time', 'Destination',
       'Total_Fare', 'dummy_comma1', 'dummy_comma2'],
      dtype='object')

In [5]:
data['Dept_Date'] = pd.to_datetime(data.Dept_Date, errors ='coerce')

In [8]:
data['RecordDate'] = pd.to_datetime(data.RecordDate, errors ='coerce')

In [9]:
data.shape

(513519, 14)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 513519 entries, 0 to 513518
Data columns (total 14 columns):
RecordDate      513506 non-null datetime64[ns]
Airline         508842 non-null object
Flight          508842 non-null object
Dept_Date       513506 non-null datetime64[ns]
Dept_Time       508842 non-null object
Origin          513519 non-null object
Duration        508842 non-null object
Stops           508842 non-null object
Arr_Date        13 non-null object
Arr_Time        508842 non-null object
Destination     513519 non-null object
Total_Fare      508842 non-null object
dummy_comma1    2808 non-null object
dummy_comma2    2808 non-null object
dtypes: datetime64[ns](2), object(12)
memory usage: 54.8+ MB

In [16]:
data.groupby(['Dept_Date']).count()

,RecordDate,Airline,Flight,Dept_Time,Origin,Duration,Stops,Arr_Date,Arr_Time,Destination,Total_Fare,dummy_comma1,dummy_comma2
Dept_Date,,,,,,,,,,,,,
2019-11-10,48160,47828,47828,47828,48160,47828,47828,0,47828,48160,47828,377,377
2019-11-11,46673,46348,46348,46348,46673,46348,46348,0,46348,46673,46348,332,332
2019-11-12,46096,45719,45719,45719,46096,45719,45719,0,45719,46096,45719,366,366
2019-11-13,48333,47981,47981,47981,48333,47981,47981,0,47981,48333,47981,371,371
2019-11-14,47494,47132,47132,47132,47494,47132,47132,0,47132,47494,47132,392,392
2019-11-15,40392,39712,39712,39712,40392,39712,39712,0,39712,40392,39712,1,1
2019-11-16,42427,42084,42084,42084,42427,42084,42084,0,42084,42427,42084,337,337
2019-11-17,46047,45644,45644,45644,46047,45644,45644,0,45644,46047,45644,331,331
2019-11-18,36973,36765,36765,36765,36973,36765,36765,0,36765,36973,36765,301,301
2019-11-19,37993,37381,37381,37381,37993,37381,37381,0,37381,37993,37381,0,0
2019-11-20,46714,46319,46319,46319,46714,46319,46319,0,46319,46714,46319,0,0
2019-11-21,26196,25916,25916,25916,26196,25916,25916,0,25916,26196,25916,0,0
2019-11-22,8,0,0,0,8,0,0,0,0,8,0,0,0